version: "3.9"

services:
  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    container_name: swagger-editor
    ports:
      - "8001:8080"
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml:ro
    environment:
      SWAGGER_JSON: /openapi.yaml
    restart: unless-stopped
    depends_on:
      - swagger-editor

  swagger-api:
    image: stoplight/prism:3
    container_name: swagger-api
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./api/openapi.yaml:/openapi.yaml:ro
    restart: unless-stopped
    depends_on:
      - swagger-editor
